
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'athena_dbt_demo'
version: '1.0.0'
config-version: 2

# Define variables here
vars:
  path_year: "2023"
  path_month: "01"

  # lumos_poc_table_location_a:
  #   longitude: 151.1977334
  #   latitude: -33.86048905
  #   distance_meters: 150.1
  
  # lumos_poc_table_location_b:
  #   longitude: 151.2128683
  #   latitude: -33.87025354
  #   distance_meters: 150.1

model_variables:
  lumos_poc_table_location_a: 
    longitude: '151.1977334'
    latitude: '-33.86048905'
    

# This setting configures which "profile" dbt uses for this project.
profile: 'athena_dbt_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  athena_dbt_demo:
    # Config indicated by + and applies to all files under models/example/
    prep_layer:
    # This will help to store the result in JSON
      +materialized: view
      +enabled: false
    analytics_layer:
      +materialized: table
      +enabled: false
      +external_location: "s3://datadump01/export/tbl_women_clothes_reviews_output/year=${var('path_year')}/month=${var('path_month')}"
      +format: "|"
      +bucketed_by: "['clothing_id']"
      +bucket_count: 1
    lumos_poc_table_location_a:
      +materialized: table
      +enabled: true
      +external_location: "s3://digifish-internal/export_lumos_poc/site=location_a/"
      +format: TEXTFILE
      +field_delimiter: "|"
      +bucketed_by: ['maid']
      +bucket_count: 1
    lumos_poc_table_location_b:
      +materialized: table
      +enabled: false
      +external_location: "s3://digifish-internal/export_lumos_poc/site=location_b/"
      +format: TEXTFILE
      +field_delimiter: "|"
      +bucketed_by: ['maid']
      +bucket_count: 1
    